server:
  port: ${SERVER_PORT}
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/users_db
    username: root
    password: password
eureka:
  instance:
    preferIpAddress: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/


